# Generated by Django 5.1.1 on 2024-09-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_goals_result_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='goals_one',
            new_name='goal_one',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='goals_two',
            new_name='goal_two',
        ),
    ]
